### ISSUE TITLE
Larael5 Login failed: Could not connect to host

### ISSUE THREAD

**Issue by hostianer** [guru-digital/ispconfig-remote-api#4]
In Laravel 5 i get a constantly "Login failed: Could not connect to host".
The API User and Passwords and IP adresse is correct.

I took your sample code and tried it without luck.

Does this package work with Laravel5 ?

**Comment by cjsewell** [comment]
Hi there, it should work fine with any framework. Keep in mind the user name and password to use is set in ispconfig under system > remote user not the same user and password you login to the web interface

**Comment by hostianer** [comment]
mh .. but i`m getting everytime a Login failed: Could not connect to host
But the remote user is 100% correct and the server ip of course also.

**Comment by cjsewell** [comment]
Sorry about the delay. I have had a chance to do some testing with larvel, and unfortunately I am unable to reproduce your issue.

This is how I tested:
```
mkdir larveltest
cd larveltest
composer create-project laravel/laravel --prefer-dist
composer require gdm/ispconfig-soap-client
```

Then updated `app\Http\Controllers\WelcomeController.php` *(Update the url, user and password on line 32)* and `resources\views\welcome.blade.php` as per [this gist](https://gist.github.com/cjsewell/647473cbc9aee493ebd0)

Then, browsing to the public folder of the project resulted in a list of client names.

**Comment by cjsewell** [comment]
If it still fails, you can start debugging using the native php soap client with the following code which requires no libraries 
```php
$ispConfigSoapLocation = "https://127.0.0.1:8080/remote/index.php";
$ispConfigUser         = "admin";
$ispConfigPassword     = "mysecurepassword";

$soapClient = new \SoapClient(null, array(
    'location' => $ispConfigSoapLocation,
    'uri'      => $ispConfigSoapLocation
));
$loginCmd   = $soapClient->login($ispConfigUser, $ispConfigPassword);
var_dump($loginCmd);
```
This should produce the following output 
```
string 'random session hash' (length=32)
```
or an exception.

If it is still failing, the generated exception should give some more insite in to what the issue is

**Comment by hostianer** [comment]
Mh ... strange.
Now i`m getting a 

```
SoapFault in routes.php line 38:
Could not connect to host
```

But the API User is definitly correct.
Is this maybe because an unsecure SSL Cert ?

I installed a dummy ISPConfig Installation.
https://188.166.41.157:8080/remote/index.php
API User: api
PW: testtest

Can you confirm that you can connect to this host ?

**Comment by cjsewell** [comment]
Ahh, I see. It is because you are using a self signed SSL cert.

I have added an optional fourth parameter, which you can pass a [stream context](http://php.net/manual/en/function.stream-context-create.php).

Using that you can disable SSL certificate verification:
e.g.
```php
$context = stream_context_create(array(
    'ssl' => array(
        'verify_peer'       => false,
        'allow_self_signed' => true
    )
));
$cp      = new \GDM\ISPConfig\SoapClient('https://188.166.41.157:8080/remote/index.php', 'api', 'testtest', $context);
var_dump($cp->serverGetAppVersion());
```

Returns me
```
array (size=1)
  'ispc_app_version' => string '3.0.5.4p5' (length=9)
```

You will have to do a `composer update gdm/ispconfig-soap-client` on your project to use the stream context.

Let me know how it goes

**Comment by hostianer** [comment]
First thanks for your awesome help +1

But this is strange, i`m still getting the same issue.
Does this maybe works with a valid comodo cert ?

**Comment by cjsewell** [comment]
Odd, I have no idea why this isnt working?
Prehaps its a php/openssl issue?

What version of PHP/ssl are you using?
I am testing on  PHP Version *5.5.15* and OpenSSL Library Version *OpenSSL 1.0.1i 6 Aug 2014*

**Comment by hostianer** [comment]
I`m just using Vagrant + Homestead 2.0.

So on your machine is is working and also with my login datas ? :)

**Comment by cjsewell** [comment]
Yes, it works fine from my dev machine using your login data.

Is the ssl module enabled?
```
php -m | grep ssl
openssl
```

**Comment by cjsewell** [comment]
Can curl on the cmd line access ISP Config?
```curl -k https://188.166.41.157:8080/```

**Comment by hostianer** [comment]
On the Server:

```
openssl version
OpenSSL 1.0.1e 11 Feb 2013
root@isp:~# php -v
PHP Deprecated:  Comments starting with '#' are deprecated in /etc/php5/cli/conf.d/ming.ini on line 1 in Unknown on line 0
PHP 5.4.36-0+deb7u3 (cli) (built: Jan  9 2015 08:07:06) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
root@isp:~# php -m | grep ssl
PHP Deprecated:  Comments starting with '#' are deprecated in /etc/php5/cli/conf.d/ming.ini on line 1 in Unknown on line 0
openssl
root@isp:~# php -m | grep openssl
PHP Deprecated:  Comments starting with '#' are deprecated in /etc/php5/cli/conf.d/ming.ini on line 1 in Unknown on line 0
openssl
```

But that`s really strange because it`s working with your dev installation ..

**Comment by cjsewell** [comment]
Im starting to think its an SSL issue with your Vagrant machine
Can curl on the cmd line access ISP Config?
```curl -k https://188.166.41.157:8080/```

**Comment by hostianer** [comment]
Yep i`m getting the html content.

**Comment by cjsewell** [comment]
Hrmm, and with php?
```
 php -r 'echo file_get_contents("https://188.166.41.157:8080/");'
```

**Comment by hostianer** [comment]
```
php -r 'echo file_get_contents("https://188.166.41.157:8080/");'
PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in Command line code on line 1
PHP Stack trace:
PHP   1. {main}() Command line code:0
PHP   2. file_get_contents() Command line code:1

Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in Command line code on line 1

Call Stack:
    0.0001     220096   1. {main}() Command line code:0
    0.0001     220192   2. file_get_contents() Command line code:1

PHP Warning:  file_get_contents(): Failed to enable crypto in Command line code on line 1
PHP Stack trace:
PHP   1. {main}() Command line code:0
PHP   2. file_get_contents() Command line code:1

Warning: file_get_contents(): Failed to enable crypto in Command line code on line 1

Call Stack:
    0.0001     220096   1. {main}() Command line code:0
    0.0001     220192   2. file_get_contents() Command line code:1

PHP Warning:  file_get_contents(https://188.166.41.157:8080/): failed to open stream: operation failed in Command line code on line 1
PHP Stack trace:
PHP   1. {main}() Command line code:0
PHP   2. file_get_contents() Command line code:1

Warning: file_get_contents(https://188.166.41.157:8080/): failed to open stream: operation failed in Command line code on line 1

Call Stack:
    0.0001     220096   1. {main}() Command line code:0
    0.0001     220192   2. file_get_contents() Command line code:1

vagrant@homestead:~/code/isp$ 
```

**Comment by cjsewell** [comment]
How about with setting verify_peer_name to false?

```
php -r 'echo file_get_contents("https://188.166.41.157:8080/",false, stream_context_create(array("ssl"=>array("verify_peer"=>false,"verify_peer_name"=>false,"allow_self_signed" => true))));'
```

**Comment by hostianer** [comment]
same result with curl - i`m getting the html content.

**Comment by cjsewell** [comment]
OK, Cool, so I think you just need  ```verify_peer_name``` to ```false``` as well in the stream context you pass to ISPConfig SoapClient

```php
$context = stream_context_create(array(
    'ssl' => array(
        'verify_peer'       => false,
        'allow_self_signed' => true,
        'verify_peer_name'  =>false
    )
));
$cp      = new \GDM\ISPConfig\SoapClient('https://188.166.41.157:8080/remote/index.php', 'api', 'testtest', $context);
var_dump($cp->serverGetAppVersion());
```

**Comment by hostianer** [comment]
BINGO :+1: 

Now It`s working ! :)

**Comment by cjsewell** [comment]
Yah! Happy APIing!

**Comment by hostianer** [comment]
Yiha ! :)

Yep a big thank you for your awesome help :+1:

**Comment by cjsewell** [comment]
No worries, thanks for your patients
