### ISSUE TITLE
Unable to find some function

### ISSUE THREAD

**Issue by mzdani** [guru-digital/ispconfig-remote-api#6]
Hello,

I can't find some function. This is the example :

``` php
...
$site   = $this->getSite($siteId);
...
```

On line 480 and 618 in SoapClient.php

And then `getSites()` and `getAllClientIds()`, for example:

``` php
...
$domains         = array_merge($reservedDomains, array_map(function($s) {
                    return $s['domain'];
                }, $this->getSites()
                ), $this->getAllClients()
        );
...
```

on line 170 in AbstractSoapClient.php

and 

``` php
...
$clientIds  = $this->getAllClientIds();
...
```

on line 151 in AbstractSoapClient.php

Can you give a correct function sir?

**Comment by xleeuwx** [comment]
Can you show the exact error line? The code 
`
$clientIds  = $this->getAllClientIds();
`
is for inside the class AbstractSoapClient if you like to use it outside the class you need to use it like this:
`
$class = new AbstractSoapClient();
$clientIds = $class->getAllClientIds();
`

**Comment by mzdani** [comment]
I got error when I use like this :
```php
use GDM\\ISPConfig\\SoapClient;

$cp = new SoapClient('http://devel.server.lc:8080/remote/index.php', 'test', 'test');
$cp->sitesWebAliasdomainAdd(2, 6, 'aliasdomain.lc');
```

and the error is 
```
 Call to undefined method GDM\\ISPConfig\\SoapClient::getSite() in /var/www/clients/client2/web12/web/SoapClient.php on line 618
```

Yes, you're correct sir. But I can't see any function with that name in AbstractSoapClient class sir. For example :
```php
public function getAllClientIds(){
...
}
```

or `getSite()` function in SoapClient.php.

**Comment by xleeuwx** [comment]
I have found the problem already, if you can see into my commit: https://github.com/xleeuwx/ispconfig-remote-api/commit/e34c1aecbc4e09ec20ba3949855d59779142e658 there are functions renamed but not all are renamed... so you can check te commits to see wat is te correct function :)

**Comment by mzdani** [comment]
Yep, that's right sir. I already check and it's good. Thank you sir. :+1:
